services:
  - type: web
    name: companies-house-monitor
    env: python
    startCommand: python main.py
    envVars:
      - key: API_KEY
        sync: false
      - key: SSE_URL
        value: https://stream.companieshouse.gov.uk/
      - key: DATABASE_FILE
        value: ./companies.db
      - key: PORT
        value: 8000
